#pragma once


enum SUBSAMPLE_MODE
{
	SUBSAMPLE_2X2 = 0,
	SUBSAMPLE_2X2_WITH_GAUSSIAN,
	SUBSAMPLE_4X4,
	SUBSAMPLE_4X4_WITH_GAUSSIAN,
	BINNING_2X2,
};

enum SUBSAMPLE_INTERPOLATION_MODE
{
	SUBSAMPLE_INTERPOLATION_NEAREST = 0,
	SUBSAMPLE_INTERPOLATION_LINEAR,
	SUBSAMPLE_INTERPOLATION_AREA,
	SUBSAMPLE_INTERPOLATION_CUBIC,
};

enum DIFF_DIRECTION
{
	DIFF_DIRECTION_CENTER = 0,
	DIFF_DIRECTION_LEFT,
	DIFF_DIRECTION_RIGHT,

};

enum DIFF_PARTIAL_MODE
{
	DIFF_PARTIAL_OPENCV = 0,
	DIFF_PARTIAL_CPP,
};

enum LAPLACIAN_MODE
{
	LAPLACIAN_OPENCV = 0,
};

enum class MODE_MEDIAN2D
{
	OPENCV = 0,
	//OPENCV_UMAT,
	//OPENCV_CUDA,
	CUSTOM_CPP,
	CUSTOM_CUDA,
	//CUSTOM_CPP_FINITE_ONLY,
	//CUSTOM_CUDA_FINITE_ONLY,
};

enum ANISOTROPIC_DIFFUSION_MODE
{
	ANISOTROPIC_DIFFUSION_OPENCV = 0,
	ANISOTROPIC_DIFFUSION_CPP,
	ANISOTROPIC_DIFFUSION_CPP_V2,
};

enum DOMAIN_TRANSFORM_MODE
{
	VERSION_1 = 0,
	NORMALIZED_CONVOLUTION,
	INTERPOLATED_CONVOLUTION,
	RECURSIVE_FILTER,
};